# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py313"
line-length = 120

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN101", # Missing type annotation for `self` in method
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
    "E203", # whitespace before ':' (Black compatibility)
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.isort]
force-single-line = false
known-first-party = ["custom_components", "homeassistant"]

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
